### ISSUE TITLE
A way to update current project template

### ISSUE THREAD

**Issue by kkharji** [yusdacra/rust-nix-templater#19]
I don't think this would be feasible, but it would nice to keep up with rust-nix-templater future releases by regenerating the current project.

I'm going to update it manually soon and start using toml files for all my project configuration but wanted to share this pain point.

**Comment by 90-008** [comment]
I implemented this with https://github.com/yusdacra/nix-cargo-integration. Currently what rust-nix-templater does is make a flake using `nix-cargo-integration`. To get new features and fixes all a user needs to do is `nix flake update`. The only pain point is that this doesn't apply to CI files, but they aren't updated as frequently as the Nix files so that is probably OK.

**Comment by kkharji** [comment]
Agree, I think when the project becomes tstable this won't be an issue so closing for now
